### ISSUE TITLE
In caso di nessuna immagine per X prodotto, non deve mostrare la slideshow

### ISSUE THREAD

**Issue by AMike01** [AMike01/ProgettoTecWeb#26]

**Comment by Alcky26** [comment]
è possibile inserire un prodotto nuovo non mettendo un immagine? se si allora dobbiamo fare questa distinzione, se no allora è ok perchè i prodotti attuali sono di test e quindi possono non avere immagini

**Comment by Alcky26** [comment]
risolto ma ora è brutto, nel senso che la pagina è completamente testo e nemmeno ben indentato, come sistemiamo?

**Comment by AMike01** [comment]
Potrei direttamente spostare l'aggiunta delle immagini su prodotto, tanto penso sia un lavoro di copia incolla, ed obbligare che ci sia almeno una immagine per ogni prodotto.

**Comment by Alcky26** [comment]
meglio
