### ISSUE TITLE
Breadcrumb non cliccabile in catalogo

### ISSUE THREAD

**Issue by alessiobarraco** [AMike01/ProgettoTecWeb#33]
Esempio: Catalogo -> Vai alla lista delle categorie
La breadcrumb mostra: Home >> Catalogo >> Categorie. "Catalogo" non porta alla pagina generale Catalogo.

**Comment by AMike01** [comment]
Aggiunta link dinamici, ho comunque dei dubbi a riguardo del GET.
Oggi pomeriggio ne parliamo
