### ISSUE TITLE
Quando viene eliminato un prodotto, appare il messaggio "Non hai selezionato nessuna immagine!"

### ISSUE THREAD

**Issue by alessiobarraco** [AMike01/ProgettoTecWeb#49]
Inoltre appaiono i seguenti warning:
Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 44

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 44

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 49

Warning: Trying to access array offset on value of type null incatalogo_handler.php on line 49

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 50

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 50

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 53

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 61

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 61

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 94

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 94

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 112

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 112

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 116

Warning: Trying to access array offset on value of type null in catalogo_handler.php on line 116

**Comment by AMike01** [comment]
Bug fix fatto ancora ieri
